# Form implementation generated from reading ui file 'expence_tracker.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 768)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(154, 253, 255, 255), stop:1 rgba(102, 111, 206, 255));\n"
"font-family: Cambria Math")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.balance_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.balance_frame.setStyleSheet("background-color: rgba(255, 255, 255, 70);\n"
"border: 1px solid rgba(255, 255, 255, 80);\n"
"border-radius: 7px")
        self.balance_frame.setObjectName("balance_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.balance_frame)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.balance_label = QtWidgets.QLabel(parent=self.balance_frame)
        self.balance_label.setStyleSheet("font-weight: bold;\n"
"font-size: 25pt;\n"
"background-color: none;\n"
"border: none;\n"
"")
        self.balance_label.setObjectName("balance_label")
        self.verticalLayout.addWidget(self.balance_label)
        self.balance_sum = QtWidgets.QLabel(parent=self.balance_frame)
        self.balance_sum.setStyleSheet("font-size: 30pt;\n"
"background-color: none;\n"
"border: none;\n"
"")
        self.balance_sum.setObjectName("balance_sum")
        self.verticalLayout.addWidget(self.balance_sum)
        self.income = QtWidgets.QHBoxLayout()
        self.income.setSpacing(0)
        self.income.setObjectName("income")
        self.income_icon = QtWidgets.QLabel(parent=self.balance_frame)
        self.income_icon.setMaximumSize(QtCore.QSize(24, 16777215))
        self.income_icon.setStyleSheet("background-color: none;\n"
"border: none;\n"
"padding-top: 10px \n"
"")
        self.income_icon.setText("")
        self.income_icon.setPixmap(QtGui.QPixmap("icons/Increase.svg"))
        self.income_icon.setObjectName("income_icon")
        self.income.addWidget(self.income_icon)
        self.income_label = QtWidgets.QLabel(parent=self.balance_frame)
        self.income_label.setStyleSheet("font-weight: bold;\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;\n"
"padding-top: 10px \n"
"")
        self.income_label.setObjectName("income_label")
        self.income.addWidget(self.income_label)
        self.verticalLayout.addLayout(self.income)
        self.income_sum = QtWidgets.QLabel(parent=self.balance_frame)
        self.income_sum.setStyleSheet("font-size: 20pt;\n"
"background-color: none;\n"
"border: none;\n"
"")
        self.income_sum.setObjectName("income_sum")
        self.verticalLayout.addWidget(self.income_sum)
        self.outcome = QtWidgets.QHBoxLayout()
        self.outcome.setSpacing(0)
        self.outcome.setObjectName("outcome")
        self.outcome_icon = QtWidgets.QLabel(parent=self.balance_frame)
        self.outcome_icon.setMaximumSize(QtCore.QSize(24, 16777215))
        self.outcome_icon.setStyleSheet("background-color: none;\n"
"border: none;\n"
"padding-top: 10px \n"
"")
        self.outcome_icon.setText("")
        self.outcome_icon.setPixmap(QtGui.QPixmap("icons/Decrease.svg"))
        self.outcome_icon.setObjectName("outcome_icon")
        self.outcome.addWidget(self.outcome_icon)
        self.outcome_label = QtWidgets.QLabel(parent=self.balance_frame)
        self.outcome_label.setStyleSheet("font-weight: bold;\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;\n"
"padding-top: 10px \n"
"")
        self.outcome_label.setObjectName("outcome_label")
        self.outcome.addWidget(self.outcome_label)
        self.verticalLayout.addLayout(self.outcome)
        self.outcome_sum = QtWidgets.QLabel(parent=self.balance_frame)
        self.outcome_sum.setStyleSheet("font-size: 20pt;\n"
"background-color: none;\n"
"border: none;\n"
"")
        self.outcome_sum.setObjectName("outcome_sum")
        self.verticalLayout.addWidget(self.outcome_sum)
        self.horizontalLayout_8.addWidget(self.balance_frame)
        self.categories_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.categories_frame.setStyleSheet("background-color: rgba(255, 255, 255, 70);\n"
"border: 1px solid rgba(255, 255, 255, 80);\n"
"border-radius: 7px")
        self.categories_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.categories_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.categories_frame.setObjectName("categories_frame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.categories_frame)
        self.verticalLayout_20.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.categories_label = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(20)
        font.setBold(True)
        self.categories_label.setFont(font)
        self.categories_label.setStyleSheet("font-weight: bold;\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.categories_label.setObjectName("categories_label")
        self.verticalLayout_20.addWidget(self.categories_label)
        self.groceries = QtWidgets.QHBoxLayout()
        self.groceries.setObjectName("groceries")
        self.groceries_icon = QtWidgets.QLabel(parent=self.categories_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groceries_icon.sizePolicy().hasHeightForWidth())
        self.groceries_icon.setSizePolicy(sizePolicy)
        self.groceries_icon.setMaximumSize(QtCore.QSize(24, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        self.groceries_icon.setFont(font)
        self.groceries_icon.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;")
        self.groceries_icon.setText("")
        self.groceries_icon.setPixmap(QtGui.QPixmap("icons/Shopping cart.svg"))
        self.groceries_icon.setObjectName("groceries_icon")
        self.groceries.addWidget(self.groceries_icon)
        self.groceries_label = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        self.groceries_label.setFont(font)
        self.groceries_label.setStyleSheet("font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;")
        self.groceries_label.setObjectName("groceries_label")
        self.groceries.addWidget(self.groceries_label)
        self.groceries_sum = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.groceries_sum.setFont(font)
        self.groceries_sum.setStyleSheet("font-size: 16pt;\n"
"background-color: none;\n"
"border: none;")
        self.groceries_sum.setLineWidth(0)
        self.groceries_sum.setObjectName("groceries_sum")
        self.groceries.addWidget(self.groceries_sum)
        self.verticalLayout_20.addLayout(self.groceries)
        self.entertainment = QtWidgets.QHBoxLayout()
        self.entertainment.setObjectName("entertainment")
        self.entertainment_icon = QtWidgets.QLabel(parent=self.categories_frame)
        self.entertainment_icon.setMaximumSize(QtCore.QSize(24, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        self.entertainment_icon.setFont(font)
        self.entertainment_icon.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;")
        self.entertainment_icon.setText("")
        self.entertainment_icon.setPixmap(QtGui.QPixmap("icons/Spa.svg"))
        self.entertainment_icon.setObjectName("entertainment_icon")
        self.entertainment.addWidget(self.entertainment_icon)
        self.entertainment_label = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        self.entertainment_label.setFont(font)
        self.entertainment_label.setStyleSheet("font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;")
        self.entertainment_label.setObjectName("entertainment_label")
        self.entertainment.addWidget(self.entertainment_label)
        self.entertainment_sum = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.entertainment_sum.setFont(font)
        self.entertainment_sum.setStyleSheet("font-size: 16pt;\n"
"background-color: none;\n"
"border: none;")
        self.entertainment_sum.setLineWidth(0)
        self.entertainment_sum.setObjectName("entertainment_sum")
        self.entertainment.addWidget(self.entertainment_sum)
        self.verticalLayout_20.addLayout(self.entertainment)
        self.pharmacy = QtWidgets.QHBoxLayout()
        self.pharmacy.setObjectName("pharmacy")
        self.pharmacy_icon = QtWidgets.QLabel(parent=self.categories_frame)
        self.pharmacy_icon.setMaximumSize(QtCore.QSize(24, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        self.pharmacy_icon.setFont(font)
        self.pharmacy_icon.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;")
        self.pharmacy_icon.setText("")
        self.pharmacy_icon.setPixmap(QtGui.QPixmap("icons/Medicine.svg"))
        self.pharmacy_icon.setObjectName("pharmacy_icon")
        self.pharmacy.addWidget(self.pharmacy_icon)
        self.pharmacy_label = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        self.pharmacy_label.setFont(font)
        self.pharmacy_label.setStyleSheet("font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;")
        self.pharmacy_label.setObjectName("pharmacy_label")
        self.pharmacy.addWidget(self.pharmacy_label)
        self.pharmacy_sum = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.pharmacy_sum.setFont(font)
        self.pharmacy_sum.setStyleSheet("font-size: 16pt;\n"
"background-color: none;\n"
"border: none;")
        self.pharmacy_sum.setLineWidth(0)
        self.pharmacy_sum.setObjectName("pharmacy_sum")
        self.pharmacy.addWidget(self.pharmacy_sum)
        self.verticalLayout_20.addLayout(self.pharmacy)
        self.other = QtWidgets.QHBoxLayout()
        self.other.setObjectName("other")
        self.other_icon = QtWidgets.QLabel(parent=self.categories_frame)
        self.other_icon.setMaximumSize(QtCore.QSize(24, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        self.other_icon.setFont(font)
        self.other_icon.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;")
        self.other_icon.setText("")
        self.other_icon.setPixmap(QtGui.QPixmap("icons/Package.svg"))
        self.other_icon.setObjectName("other_icon")
        self.other.addWidget(self.other_icon)
        self.other_label = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        self.other_label.setFont(font)
        self.other_label.setStyleSheet("font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;")
        self.other_label.setObjectName("other_label")
        self.other.addWidget(self.other_label)
        self.other_sum = QtWidgets.QLabel(parent=self.categories_frame)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.other_sum.setFont(font)
        self.other_sum.setStyleSheet("font-size: 16pt;\n"
"background-color: none;\n"
"border: none;")
        self.other_sum.setLineWidth(0)
        self.other_sum.setObjectName("other_sum")
        self.other.addWidget(self.other_sum)
        self.verticalLayout_20.addLayout(self.other)
        self.horizontalLayout_8.addWidget(self.categories_frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.transactions = QtWidgets.QHBoxLayout()
        self.transactions.setObjectName("transactions")
        self.transaction_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.transaction_add.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Add cart.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.transaction_add.setIcon(icon)
        self.transaction_add.setIconSize(QtCore.QSize(24, 24))
        self.transaction_add.setObjectName("transaction_add")
        self.transactions.addWidget(self.transaction_add)
        self.transaction_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.transaction_edit.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/Edit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.transaction_edit.setIcon(icon1)
        self.transaction_edit.setIconSize(QtCore.QSize(24, 24))
        self.transaction_edit.setObjectName("transaction_edit")
        self.transactions.addWidget(self.transaction_edit)
        self.transaction_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.transaction_delete.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/Delete.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.transaction_delete.setIcon(icon2)
        self.transaction_delete.setIconSize(QtCore.QSize(24, 24))
        self.transaction_delete.setObjectName("transaction_delete")
        self.transactions.addWidget(self.transaction_delete)
        self.verticalLayout_3.addLayout(self.transactions)
        self.transactions_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transactions_table.sizePolicy().hasHeightForWidth())
        self.transactions_table.setSizePolicy(sizePolicy)
        self.transactions_table.setMinimumSize(QtCore.QSize(1063, 0))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(22)
        self.transactions_table.setFont(font)
        self.transactions_table.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.transactions_table.setAutoFillBackground(False)
        self.transactions_table.setStyleSheet("QTableWidget {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"}\n"
"\n"
"QTableWidget:section {\n"
"background-color: rgba(53, 53, 53);\n"
"border: none;\n"
"height: 50px;\n"
"}\n"
"\n"
"QTableWidget:item {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}\n"
"\n"
"QTableWidget:item:selected {\n"
"border: none;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.transactions_table.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.transactions_table.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.transactions_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.transactions_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.transactions_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.transactions_table.setShowGrid(False)
        self.transactions_table.setColumnCount(6)
        self.transactions_table.setObjectName("transactions_table")
        self.transactions_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        item.setBackground(QtGui.QColor(111, 135, 158, 0))
        self.transactions_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(5, item)
        self.transactions_table.horizontalHeader().setVisible(True)
        self.transactions_table.horizontalHeader().setCascadingSectionResizes(False)
        self.transactions_table.horizontalHeader().setDefaultSectionSize(177)
        self.transactions_table.horizontalHeader().setHighlightSections(True)
        self.transactions_table.horizontalHeader().setMinimumSectionSize(43)
        self.transactions_table.horizontalHeader().setSortIndicatorShown(False)
        self.transactions_table.horizontalHeader().setStretchLastSection(True)
        self.transactions_table.verticalHeader().setCascadingSectionResizes(False)
        self.transactions_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.transactions_table)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Expence Tracker"))
        self.balance_label.setText(_translate("MainWindow", "Баланс"))
        self.balance_sum.setText(_translate("MainWindow", "{balance}"))
        self.income_label.setText(_translate("MainWindow", "Доходы"))
        self.income_sum.setText(_translate("MainWindow", "{sum}"))
        self.outcome_label.setText(_translate("MainWindow", "Расходы"))
        self.outcome_sum.setText(_translate("MainWindow", "{sum}"))
        self.categories_label.setText(_translate("MainWindow", "Категории трат"))
        self.groceries_label.setText(_translate("MainWindow", "Продукты"))
        self.groceries_sum.setText(_translate("MainWindow", "{sum}"))
        self.entertainment_label.setText(_translate("MainWindow", "Развлечения"))
        self.entertainment_sum.setText(_translate("MainWindow", "{sum}"))
        self.pharmacy_label.setText(_translate("MainWindow", "Аптеки"))
        self.pharmacy_sum.setText(_translate("MainWindow", "{sum}"))
        self.other_label.setText(_translate("MainWindow", "Другое"))
        self.other_sum.setText(_translate("MainWindow", "{sum}"))
        self.transaction_add.setText(_translate("MainWindow", "Добавить транзакцию"))
        self.transaction_edit.setText(_translate("MainWindow", "Редактировать транзакцию"))
        self.transaction_delete.setText(_translate("MainWindow", "Удалить транзакцию"))
        item = self.transactions_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.transactions_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.transactions_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Категория"))
        item = self.transactions_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Описание"))
        item = self.transactions_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.transactions_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Статус"))
