# Form implementation generated from reading ui file 'new_transaction.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(473, 500)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(154, 253, 255, 255), stop:1 rgba(102, 111, 206, 255));\n"
"font-family: Cambria Math")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 451, 481))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 70);\n"
"border: 1px solid rgba(255, 255, 255, 80);\n"
"border-radius: 7px")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.new_transaction = QtWidgets.QLabel(parent=self.frame)
        self.new_transaction.setGeometry(QtCore.QRect(0, 10, 451, 71))
        self.new_transaction.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.new_transaction.setStyleSheet("font-weight: bold;\n"
"font-size: 25pt;\n"
"background-color: none;\n"
"border: none;")
        self.new_transaction.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.new_transaction.setObjectName("new_transaction")
        self.date_choosing = QtWidgets.QDateEdit(parent=self.frame)
        self.date_choosing.setGeometry(QtCore.QRect(110, 80, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(15)
        self.date_choosing.setFont(font)
        self.date_choosing.setStyleSheet("QDateTimeEdit::calendarPopup {\n"
"background-color: #00ff00;\n"
"color: #ff00ff;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"font-size: 15pt;\n"
"color: rgb(51, 51, 51);\n"
"background-color: white;\n"
"selection-background-color: rgb(129, 162, 199);\n"
"selection-color:rgba(230, 230, 230) ;\n"
"}")
        self.date_choosing.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 11, 19), QtCore.QTime(10, 0, 0)))
        self.date_choosing.setCalendarPopup(True)
        self.date_choosing.setDate(QtCore.QDate(2024, 11, 19))
        self.date_choosing.setObjectName("date_choosing")
        self.description_edit = QtWidgets.QLineEdit(parent=self.frame)
        self.description_edit.setGeometry(QtCore.QRect(10, 180, 431, 81))
        self.description_edit.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.description_edit.setToolTipDuration(-1)
        self.description_edit.setAccessibleDescription("")
        self.description_edit.setAutoFillBackground(False)
        self.description_edit.setStyleSheet("font-size: 15pt")
        self.description_edit.setObjectName("description_edit")
        self.sum_edit = QtWidgets.QLineEdit(parent=self.frame)
        self.sum_edit.setGeometry(QtCore.QRect(10, 270, 431, 81))
        self.sum_edit.setStyleSheet("font-size: 15pt")
        self.sum_edit.setObjectName("sum_edit")
        self.increase_decrease = QtWidgets.QComboBox(parent=self.frame)
        self.increase_decrease.setGeometry(QtCore.QRect(10, 360, 431, 41))
        self.increase_decrease.setStyleSheet("font-size: 15pt")
        self.increase_decrease.setObjectName("increase_decrease")
        self.increase_decrease.addItem("")
        self.increase_decrease.addItem("")
        self.date_label = QtWidgets.QLabel(parent=self.frame)
        self.date_label.setGeometry(QtCore.QRect(270, 80, 121, 31))
        self.date_label.setStyleSheet("background-color: none;\n"
"border: none;\n"
"font-size: 16pt")
        self.date_label.setObjectName("date_label")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 420, 421, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 60);\n"
"border: 1px solid rgba(255, 255, 255, 70);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px;\n"
"font-size: 15pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Add.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.choosing_category = QtWidgets.QComboBox(parent=self.frame)
        self.choosing_category.setGeometry(QtCore.QRect(10, 130, 431, 41))
        self.choosing_category.setStyleSheet("font-size: 15pt")
        self.choosing_category.setCurrentText("")
        self.choosing_category.setObjectName("choosing_category")
        self.choosing_category.addItem("")
        self.choosing_category.addItem("")
        self.choosing_category.addItem("")
        self.choosing_category.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.new_transaction.setText(_translate("Dialog", "Новая транзакция"))
        self.description_edit.setPlaceholderText(_translate("Dialog", "Описание покупки"))
        self.sum_edit.setPlaceholderText(_translate("Dialog", "Сумма"))
        self.increase_decrease.setItemText(0, _translate("Dialog", "Доход"))
        self.increase_decrease.setItemText(1, _translate("Dialog", "Расход"))
        self.date_label.setText(_translate("Dialog", "Дата"))
        self.pushButton.setText(_translate("Dialog", "Сохранить"))
        self.choosing_category.setPlaceholderText(_translate("Dialog", "Название категории"))
        self.choosing_category.setItemText(0, _translate("Dialog", "Продукты"))
        self.choosing_category.setItemText(1, _translate("Dialog", "Развлечения"))
        self.choosing_category.setItemText(2, _translate("Dialog", "Аптеки"))
        self.choosing_category.setItemText(3, _translate("Dialog", "Другое"))
